# Generated by Django 3.2 on 2023-03-05 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230226_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
