# Generated by Django 3.2 on 2023-03-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.FloatField(verbose_name='Frais')),
            ],
            options={
                'verbose_name': 'DeliveryFee',
                'verbose_name_plural': 'DeliveryFees',
            },
        ),
    ]
