# Generated by Django 3.2 on 2023-03-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generateur


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20230226_1531'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.generateur.generate_code, max_length=50, verbose_name='Code')),
                ('status', models.CharField(choices=[('R', 'Reçue'), ('T', 'Traitée'), ('E', 'Expédiée'), ('L', 'Livrée')], max_length=1, verbose_name='Status')),
                ('order_time', models.DateTimeField(auto_now=True, verbose_name='Heure de Commande')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'expédition")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantite')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrderDetails',
            },
        ),
    ]
