# Generated by Django 3.2 on 2023-03-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230304_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Casts'},
        ),
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'verbose_name': 'CartDetail', 'verbose_name_plural': 'CartDetails'},
        ),
    ]
