# Generated by Django 3.2 on 2023-03-05 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230305_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure de Commande'),
        ),
    ]
