# Generated by Django 4.0 on 2023-03-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
